config/routes.rb
Rails.application.routes.draw do
  root "resumes#index"
  resources :resumes do
    resources :authors, module: :resumes
    resources :projects, module: :resumes
    resources :experiences, module: :resumes
    resources :educations, module: :resumes
    resources :skills, module: :resumes
    member do
      get 'corporate'
    end
    # get '/download_resume', to: 'resumes#download_resume', as: 'download_resume'
  end
end

app/models/resume.rb
class Resume < ApplicationRecord
  has_one :author, dependent: :destroy
  has_one :project, dependent: :destroy
  has_many :project_line_items, through: :project
  has_one :skill, dependent: :destroy
  has_many :skill_line_items, through: :skill
  has_one :experience, dependent: :destroy
  has_many :experience_line_items, through: :experience
  has_one :education, dependent: :destroy
  has_many :education_line_items, through: :education
  after_create :create_associations

  validates :name, presence: :true

  def create_associations
    Author.create!(resume_id: self.id)
    Project.create!(resume_id: self.id)
    Skill.create!(resume_id: self.id)
    Education.create!(resume_id: self.id)
    Experience.create!(resume_id: self.id)
  end
end

app/controllers/resumes/authors_controller.rb
class Resumes::AuthorsController < ApplicationController
  before_action :set_resume
  before_action :set_author, only: [:edit, :update]
  before_action :duplicate, only: :edit

  def new
    @author = Author.new
  end

  def create
    @author = Author.create!(author_params)
    if @author.save
      redirect_to resume_path(@resume)
    end
  end

  def edit; end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      redirect_to resume_path(@resume)
    end
  end

  private

  def set_resume
    @resume = Resume.find(params[:resume_id])
  end

  def set_author
    @author = Author.find(params[:id])
  end

  def duplicate
    if params[:duplicate].present?
      @author.copy_from_last_version
      redirect_to edit_resume_author_path(@resume, @author)
    end
  end

  def author_params
    params.require(:author).permit(:first_name, :last_name, :email, :phone_number, :website, :bio, :title, :resume_id)
  end
end

app/controllers/resumes/educations_controller.rb
class Resumes::EducationsController < ApplicationController
  before_action :set_resume
  before_action :set_education, only: [:edit, :update]
  before_action :duplicate, only: :edit

  def new
    @education = Education.new
  end

  def create
    @education = Education.create!(education_params)
    if @education.save
      redirect_to resume_path(@resume)
    end
  end

  def edit; end

  def update
    if @education.update(education_params)
      redirect_to resume_path(@resume)
    else
      render :edit
    end
  end

  private

  def set_education
    @education = Education.find(params[:id])
  end

  def set_resume
    @resume = Resume.find(params[:resume_id])
  end

  def duplicate
    if params[:duplicate].present?
      @education.copy_from_last_version
    end
  end

  def education_params
    params
      .require(:education)
      .permit(
        :resume_id,
        education_line_items_attributes: [:_destroy, :name, :focus, :start_year, :end_year, :description, :id, :education_id]
      )
  end
end

app/controllers/resumes/experiences_controller.rb
class Resumes::ExperiencesController < ApplicationController
  before_action :set_resume
  before_action :set_experience, only: [:edit, :update]
  before_action :duplicate, only: :edit

  def new
    @experience = Experience.new
    if params[:duplicate].present?
      @experience.copy_from_last_version
      if @resume.experience.experience_line_items.present?
        redirect_to edit_resume_experience_path(@resume, @resume.experience)
      end
    end
  end

  def create
    @experience = Experience.create!(experience_params)
    if @experience.save
      redirect_to resume_path(@resume)
    end
  end

  def edit; end

  def update
    if @experience.update(experience_params)
      redirect_to resume_path(@resume)
    else
      render :edit
    end
  end

  private

  def set_experience
    @experience = Experience.find(params[:id])
  end

  def set_resume
    @resume = Resume.find(params[:resume_id])
  end

  def duplicate
    if params[:duplicate].present?
      @experience.copy_from_last_version
    end
  end

  def experience_params
    params
      .require(:experience)
      .permit(
        :resume_id,
        experience_line_items_attributes: [:_destroy, :name, :title, :start_year, :end_year, :description, :id, :experience_id]
      )
  end
end

app/controllers/resumes/projects_controller.rb
class Resumes::ProjectsController < ApplicationController
  before_action :set_resume
  before_action :set_project, only: [:edit, :update]
  before_action :duplicate, only: :edit

  def new
    @project = Project.new
  end

  def create
    @project = Project.create!(project_params)
    if @project.save
      redirect_to resume_path(@resume)
    end
  end

  def edit;end

  def update
    if @project.update(project_params)
      redirect_to resume_path(@resume)
    else
      render :edit
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def set_resume
    @resume = Resume.find(params[:resume_id])
  end

  def duplicate
    if params[:duplicate].present?
      @project.copy_from_last_version
    end
  end

  def project_params
    params
      .require(:project)
      .permit(
        :resume_id,
        project_line_items_attributes: [:_destroy, :name, :description, :start_year, :end_year, :tools, :id, :project_id]
      )
  end
end

app/controllers/resumes/skills_controller.rb
class Resumes::SkillsController < ApplicationController
  before_action :set_resume
  before_action :set_skill, only: [:edit, :update]
  before_action :duplicate, only: :edit

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.create!(skill_params)
    if @skill.save
      redirect_to resume_path(@resume)
    end
  end

  def edit; end

  def update
    if @skill.update(skill_params)
      redirect_to resume_path(@resume)
    else
      render :edit
    end
  end

  private

  def set_skill
    @skill = Skill.find(params[:id])
  end

  def set_resume
    @resume = Resume.find(params[:resume_id])
  end

  def duplicate
    if params[:duplicate].present?
      @skill.copy_from_last_version
    end
  end

  def skill_params
    params
      .require(:skill)
      .permit(
        :resume_id,
        skill_line_items_attributes: [:_destroy, :name, :description, :id, :skill_id]
      )
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume
  before_action :set_current_template, only: [:show, :corporate]
  include Groverable

  def index
    @resumes = Resume.all
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.create(resume_params)
    if @resume.save
      redirect_to resumes_path
    end
  end

  def show
    respond_to do |format|
      format.html
      format.pdf { download_resume }
    end
  end

  def corporate
    respond_to do |format|
      format.html
      format.pdf { download_resume }
    end
  end

  private

  def set_resume
    @resume = Resume.find_by(id: params[:id])
  end

  def resume_params
    params.require(:resume).permit(:name, :description)
  end

  def download_resume
    render_pdf(ResumesController, @template, @resume)
  end


  def set_current_template
    case params[:action]
    when 'show'
      @template = 'resumes/show'
    else 'corporate'
      @template = 'resumes/corporate'
    end
  end
end

app/views/resumes/_form.html.erb
<%= form_with model: @resume, class: "bg-white shadow border p-4 m-2 rounded" do |f| %>
  <div class="mb-4">
    <%= f.label :name, class: 'block' %>
    <%= f.text_field :name, class: "border p-2 w-full" %>
  </div>
  <div class="mb-4">
    <%= f.label :description, class: 'block' %>
    <%= f.text_area :description, class: "border p-2 w-full" %>
  </div>
  <%= f.submit class: "bg-blue-400 text-white rounded text-center p-2" %>
<% end %>

app/views/resumes/corporate.html.erb
<%= render "layouts/nav" %>
<div class="max-w-5xl mx-auto p-4">
  <div class="flex justify-between items-center w-full">
    <%= link_to corporate_resume_path(id: @resume.id, format: :pdf), class: "print:hidden" do  %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="inline-block align-middle" viewBox="0 0 16 16">
        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
        <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
      </svg>
      <span class="inline-block align-middle">Download PDF</span>
    <% end %>
    <div class="flex flex-wrap space-x-2 text-sm">
      <%= link_to 'Original', resume_path(id: @resume.id), class: 'underline' %>
      <%= link_to 'Corporate', corporate_resume_path(id: @resume.id), class: 'underline' %>
    </div>
  </div>
  <div class="my-4 bg-white shadow p-4 rounded font-sans print:shadow-none print:rounded-none print:bg-none print:p-0 print:m-0">
    <%= render partial: "resumes/authors/author_section_corporate" %>
    <%= render partial: "resumes/projects/project_section_corporate" %>
    <%= render partial: "resumes/skills/skill_section_corporate" %>
    <%= render partial: "resumes/experiences/experience_section_corporate" %>
    <%= render partial: "resumes/educations/education_section_corporate" %>
  </div>
</div>
<div class="fixed bottom-10 right-12 print:hidden">
  <%= button_tag "⤴️", class: "text-white rounded-full h-16 w-16 shadow p-4 text-center bg-blue-500 hover:bg-blue-400 active:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-300", data: { controller: "to-top", action: "click->to-top#bringToTop" } %>
</div>

app/views/resumes/index.html.erb
<div class="max-w-lg mx-auto p-2">
<p>Your resumes</p>
<div class="bg-white shadow border p-4 m-2 rounded">
  <% @resumes.each do |resume| %>
    <div class="mb-4 underline text-blue-400 hover:text-blue-300">
      <%= link_to resume_path(resume) do %>
        <%= resume.name %> - <%= resume.created_at.strftime('%Y-%m-%d') %>
      <% end %>
    </div>
  <% end %>
  <%= link_to 'New resume', new_resume_path, class: 'block text-center underline text-blue-400 hover:text-blue-300' %>
</div>
</div>

app/views/resumes/new.html.erb
<div class="max-w-lg mx-auto p-2">
  <p class="text-center mb-4">New Resume</p>
  <%= render partial: 'form' %>
</div>

app/views/resumes/show.html.erb
<%= render "layouts/nav" %>
<div class="max-w-5xl mx-auto p-4">
  <%= link_to resume_path(id: @resume.id, format: :pdf), class: "print:hidden" do  %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="inline-block align-middle" viewBox="0 0 16 16">
      <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
      <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
    </svg>
    <span class="inline-block align-middle">Download PDF</span>
  <% end %>
  <div class="my-4 bg-white shadow p-4 rounded font-sans print:m-0 print:shadow-none print:rounded-none print:bg-none print:p-0">
    <%= render partial: "resumes/authors/author_section" %>
    <%= render partial: "resumes/projects/project_section" %>
    <%= render partial: "resumes/skills/skill_section" %>
    <%= render partial: "resumes/experiences/experience_section" %>
    <%= render partial: "resumes/educations/education_section" %>
  </div>
</div>
<div class="fixed bottom-10 right-12 print:hidden">
  <%= button_tag "⤴️", class: "text-white rounded-full h-16 w-16 shadow p-4 text-center bg-blue-500 hover:bg-blue-400 active:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-300", data: { controller: "to-top", action: "click->to-top#bringToTop" } %>
</div>