config/routes.rb
Rails.application.routes.draw do
  root "resumes#index"
  resources :resumes do
    resources :authors, module: :resumes
    resources :projects, module: :resumes
    resources :experiences, module: :resumes
    resources :educations, module: :resumes
    resources :skills, module: :resumes
    member do
      get 'corporate'
    end
    # get '/download_resume', to: 'resumes#download_resume', as: 'download_resume'
  end
end

app/views/layouts/_nav.html.erb
<div class="max-w-5xl mx-auto p-4 print:hidden ">
  <nav class="flex justify-between items-center bg-white rounded p-2">
    <div>
      <% unless current_page?(resume_path(@resume)) %>
        <%= link_to "view resume", resume_path(@resume), class: "underline" %>
      <% end %>
      <% if @resume.author.present? %>
        <%= link_to "edit author", edit_resume_author_path(@resume, @resume.author), class: "underline" %>
      <% else %>
        <%= link_to "author", new_resume_author_path(@resume), class: "underline" %>
      <% end %>
      <% if @resume.project.present? %>
        <%= link_to "edit projects", edit_resume_project_path(@resume, @resume.project), class: "underline" %>
      <% else %>
        <%= link_to "projects", new_resume_project_path(@resume), class: "underline" %>
      <% end %>
      <% if @resume.skill.present? %>
        <%= link_to "edit skills", edit_resume_skill_path(@resume, @resume.skill), class: "underline" %>
      <% else %>
        <%= link_to "skills", new_resume_skill_path(@resume), class: "underline" %>
      <% end %>
      <% if @resume.experience.present? %>
        <%= link_to "edit experiences", edit_resume_experience_path(@resume, @resume.experience), class: "underline" %>
      <% else %>
        <%= link_to "experiences", new_resume_experience_path(@resume), class: "underline" %>
      <% end %>
      <% if @resume.education.present? %>
        <%= link_to "edit educations", edit_resume_education_path(@resume, @resume.education), class: "underline" %>
      <% else %>
        <%= link_to "educations", new_resume_education_path(@resume), class: "underline" %>
      <% end %>
    </div>
    <div>
      <%= link_to "your resumes", resumes_path, class: "underline" %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResumeBuilder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-gray-100 antialiased">
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:html_title) ? yield(:html_title) : "resume_builder" %></title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application", host: "localhost", protocol: "https" %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>